version: 2.1

commands:
  install_awscli:
    description: Install AWS CLI v2
    steps:
      - run:
          name: Install AWS CLI v2
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
  install_ansible:
    description: Install Ansible
    steps:
      - run:
          name: Install Ansible
          command: |
            sudo apt update
            sudo apt install software-properties-common -y
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible -y

orbs:
  docker: circleci/docker@2.2.0

jobs:
  init:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "thaoapp/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            make install
      - save_cache:
          paths:
            - ./venv  # TODO: Include in cache the "bin" directory
          key: v1-dependencies-{{ checksum "thaoapp/requirements.txt" }}
      - run:
          name: Run lint
          command: |
            source venv/bin/activate
            make lint
  
  deploy-app:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - install_awscli
      - run:
          name: Install dependencies
          command: |
            python --version
            python -m venv venv
            source venv/bin/activate
            make install
            make k8s-deployment


workflows:
  default:
    jobs:
      - init        
      - docker/publish:
          matrix:
            parameters:
              image: [$DOCKER_LOGIN/thaoapp]
              path: [thaoapp]
              docker-context: [thaoapp]
              deploy: [true]
              # We publish two images with different version tags: 
              # - numbered version
              # - "latest"
              # tag: ['$(<hello_app/VERSION.txt)-${CIRCLE_SHA1:0:7}', 'latest']
              tag: ['$(<thaoapp/VERSION.txt)', 'latest']
              # update-description: [true]    
          requires: [init]
      - deploy-app:
          requires: [docker/publish]
